// <auto-generated />
using System;
using Filed.PaymentGateway.DataAccess.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Filed.PaymentGateway.DataAccess.Migrations
{
    [DbContext(typeof(PaymentContext))]
    partial class PaymentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Filed.PaymentGateway.Contracts.PaymentModel.CardInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CreditCardNumber")
                        .IsRequired();

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid?>("PersonId");

                    b.Property<string>("SecurityCode")
                        .HasMaxLength(20);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Filed.PaymentGateway.Contracts.PaymentModel.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Filed.PaymentGateway.Contracts.PaymentModel.Transactions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CardInformationId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("PaymentState")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CardInformationId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Filed.PaymentGateway.Contracts.PaymentModel.CardInformation", b =>
                {
                    b.HasOne("Filed.PaymentGateway.Contracts.PaymentModel.Person")
                        .WithMany("CardInformation")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Filed.PaymentGateway.Contracts.PaymentModel.Transactions", b =>
                {
                    b.HasOne("Filed.PaymentGateway.Contracts.PaymentModel.CardInformation")
                        .WithMany("Transactions")
                        .HasForeignKey("CardInformationId");
                });
#pragma warning restore 612, 618
        }
    }
}
